"use client";
import { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import MultipleBooks from "./components/multiplebooksdisplay";
import pb from "@/app/pocketbase";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage() {
  const [isAdmin, setIsAdmin] = useState(false);

  useEffect(() => {
    if (pb.authStore.isValid) {
      const user = pb.authStore.model.id;
      if (user == "d79mfxt09efk15q") {
        setIsAdmin(true);
      }
    }
  });

  useEffect(() => {
    const handleStorageChange = (event) => {
      setDarkMode(!darkMode);
    };
    window.addEventListener("storage", handleStorageChange);
    return () => {
      window.removeEventListener("storage", handleStorageChange);
    };
  }, [localStorage.getItem("darkMode")]);

  return (
    <section className=" dark:text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-xl">
        <div>
          <Link
            href={`/addBook`}
            className={`text-black ${
              isAdmin
                ? "focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 font-mediumfocus:outline-none float-left rounded-lg bg-sand px-5 py-3 text-center text-sm hover:bg-btnHoverBlue focus:ring-4"
                : "hidden"
            }`}
          >
            Add books
          </Link>
        </div>
        <div>
          <Link
            href={`/myReviews/d79mfxt09efk15q`}
            className={`text-black ${
              isAdmin
                ? "focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 font-mediumfocus:outline-none float-left rounded-lg bg-sand px-5 py-3 text-center text-sm hover:bg-btnHoverBlue focus:ring-4"
                : "hidden"
            }`}
          >
            Edit reviews
          </Link>
        </div>
        <div
          className={`relative flex min-h-screen w-1080 flex-col justify-start self-center overflow-hidden pl-3 `}
        >
          <h1 className="self-start font-sans text-xl">Recently added</h1>
          <MultipleBooks type="recent" />
          <h1 className="self-start pt-4 pb-1 pl-3 font-sans text-xl">
            Highest rated
          </h1>
          <MultipleBooks type="top10" />
        </div>
      </main>
    </section>
  );
}
